DROP TABLE IF EXISTS NGameLists;
DROP TABLE IF EXISTS NGameGenres;
DROP TABLE IF EXISTS NGamePlatforms;
DROP TABLE IF EXISTS NUsers;
DROP TABLE IF EXISTS NGames;
DROP TABLE IF EXISTS NLists;
DROP TABLE IF EXISTS NPlatforms;
DROP TABLE IF EXISTS NGenres;
